# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - tables_correspondances_nginx_data:/data:z

  ui:
    mem_limit: 1g
    stdin_open: true
    build:
      context: ui
      dockerfile: Dockerfile.dev
    volumes:
      # Allows source folders to be watched
      - ./ui:/app

  server:
    build:
      context: server
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server:/app:z # Allows source folders to be watched
      - tables_correspondances_server_data:/data:z
    environment:
      - TABLES_CORRESPONDANCES_ENV=dev
      - TABLES_CORRESPONDANCES_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - tables_correspondances_mongodb_data:/data:z

volumes:
  tables_correspondances_mongodb_data:
    driver: local
    name: tables_correspondances_mongodb_data
  tables_correspondances_nginx_data:
    driver: local
    name: tables_correspondances_nginx_data
  tables_correspondances_server_data:
    driver: local
    name: tables_correspondances_server_data
