# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - tables_correspondances_nginx_data:/data:z

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src:z # Allows source folders to be watched
      - ./server/config:/app/config:z
      - tables_correspondances_server_data:/data:z
    environment:
      - TABLES_CORRESPONDANCES_ENV=dev
      - TABLES_CORRESPONDANCES_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - tables_correspondances_mongodb_data:/data:z

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - tables_correspondances_data_elasticsearch:/usr/share/elasticsearch/data:z
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z

  kibana:
    ports:
      - "127.0.0.1:5601:5601"
    volumes:
      - ./elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z

volumes:
  tables_correspondances_data_elasticsearch:
    driver: local
    name: tables_correspondances_data_elasticsearch
  tables_correspondances_mongodb_data:
    driver: local
    name: tables_correspondances_mongodb_data
  tables_correspondances_nginx_data:
    driver: local
    name: tables_correspondances_nginx_data
  tables_correspondances_server_data:
    driver: local
    name: tables_correspondances_server_data
