version: "2.4"
services:
  reverse_proxy:
    image: tables_correspondances_reverse_proxy
    container_name: tables_correspondances_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - tables_correspondances_network
    depends_on:
      - server
      - ui

  ui:
    image: tables_correspondances_ui
    container_name: tables_correspondances_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - tables_correspondances_network
    depends_on:
      - server

  server:
    image: tables_correspondances_server
    container_name: tables_correspondances_server
    build:
      context: server
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - tables_correspondances_network
    depends_on:
      - mongodb
    environment:
      - TABLES_CORRESPONDANCES_MONGODB_URI=mongodb://mongodb:27017/tables-correspondances?retryWrites=true&w=majority

  mongodb:
    image: mongo:5.0.2-focal
    container_name: tables_correspondances_mongodb
    command: --wiredTigerCacheSizeGB 1.8
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - tables_correspondances_network

networks:
  tables_correspondances_network:
    name: tables_correspondances_network
