import { isValideUAI } from "./utils";

const cfdStubResult = {
  result: {
    cfd: "40033002",
    cfd_outdated: false,
    date_fermeture: 1661896800000,
    specialite: null,
    niveau: "4 (BAC...)",
    intitule_long: "SERVICES DE PROXIMITE ET VIE LOCALE (BAC PRO)",
    intitule_court: "SERVICES DE PROXIMITE  VIE LOCALE",
    diplome: "BAC PROFESSIONNEL",
    libelle_court: "BAC PRO",
    niveau_formation_diplome: "400",
    rncp: {
      cfds: ["40033006", "40033002"],
      code_rncp: "RNCP34605",
      intitule_diplome: "Animation - enfance et personnes âgées",
      date_fin_validite_enregistrement: "31/08/2025",
      active_inactive: "ACTIVE",
      etat_fiche_rncp: "Publiée",
      niveau_europe: "niveau4",
      code_type_certif: "BAC PRO",
      type_certif: "Baccalauréat professionnel",
      ancienne_fiche: ["RNCP4556"],
      nouvelle_fiche: null,
      demande: 0,
      certificateurs: [
        {
          certificateur: "Ministère de l'Education nationale et de la jeunesse",
          siret_certificateur: "11004301500012",
        },
      ],
      nsf_code: "330",
      nsf_libelle: "Spécialites plurivalentes des services aux personnes",
      romes: [
        { rome: "G1203", libelle: "Animation de loisirs auprès d'enfants ou d'adolescents" },
        { rome: "G1202", libelle: "Animation d'activités culturelles ou ludiques" },
      ],
      blocs_competences: [
        {
          numero_bloc: "RNCP34605BC10",
          intitule: "Histoire géographie et enseignement moral et civique",
          liste_competences:
            "<p>- Appréhender la diversité des sociétés et la richesse des cultures <br>- Comprendre les enjeux liés au développement durable <br>- Identifier les enjeux et contraintes de la mondialisation <br>- Identifier les droits et devoirs civils, politiques, économiques et sociaux  </p>",
          modalites_evaluation:
            "<p>  <strong>Candidats de la voie scolaire dans un établissement public ou privé sous contrat, CFA ou section d’apprentissage habilité, formation professionnelle continue dans un établissement public</strong> : ponctuel écrit   </p><p><br></p><p><strong>Candidats de la voie scolaire dans un établissement privé hors contrat, CFA ou section d’apprentissage non habilité, formation professionnelle continue dans un établissement privé, CNED, candidats justifiant de 3 années d’activité professionnelle</strong> : ponctuel écrit   </p><p><br></p><p><strong>Candidats de la formation professionnelle continue dans un établissement public habilité </strong>: contrôle en cours de formation (CCF) </p>",
        },
      ],
      voix_acces: null,
      partenaires: null,
      type_enregistrement: "Enregistrement de droit",
      si_jury_ca: "Oui",
      eligible_apprentissage: true,
      created_at: "2021-03-22T21:03:54.047Z",
      last_update_at: "2021-08-11T23:15:41.774Z",
    },
    mefs: {
      mefs10: [{ mef10: "2453300211", modalite: { duree: "1", annee: "1" } }],
      mefs8: ["24533002"],
      mefs_aproximation: [],
    },
    onisep: { url: null },
    opcos: [],
  },
  messages: {
    cfd: "Trouvé dans la BCN",
    specialite: "Non fourni",
    niveau: "Ok",
    intitule_long: "Ok",
    intitule_court: "Ok",
    diplome: "Ok",
    libelle_court: "Ok",
    niveau_formation_diplome: "Ok",
    rncp: { code_rncp: "Ok" },
    mefs: { mefs10: "Ok", mefs8: "Ok", mefs_aproximation: "" },
    onisep: { url: "Non trouvé" },
  },
};

const cpStubResult = {
  result: {
    code_postal: "92600",
    code_commune_insee: "92004",
    commune: "Asnières-sur-Seine",
    num_departement: "92",
    nom_departement: "Hauts-de-Seine",
    region: "Île-de-France",
    num_region: "11",
    nom_academie: "Versailles",
    num_academie: 25,
  },
  messages: { cp: "Ok", update: "" },
};

const mef10StubResult = {
  result: {
    mef11: "23310022319",
    cfd: {
      cfd: "50022319",
      cfd_outdated: true,
      date_fermeture: 999208800000,
      specialite: null,
      niveau: "3 (CAP...)",
      intitule_long: "COKIER (CAP)",
      intitule_court: "COKIER",
      diplome: "CERTIFICAT D'APTITUDES PROFESSIONNELLES",
      libelle_court: "CAP",
      niveau_formation_diplome: "500",
    },
    rncp: {},
    onisep: {},
  },
  messages: {
    mef11: "Ok",
    cfdUpdated: "Trouvé",
    cfd: {
      cfd: "Périmé dans la BCN",
      specialite: "Non fourni",
      niveau: "Ok",
      intitule_long: "Ok",
      intitule_court: "Ok",
      diplome: "Ok",
      libelle_court: "Ok",
      niveau_formation_diplome: "Ok",
    },
    rncp: { error: "Erreur: Non trouvé" },
  },
};

const siretStubResult = {
  result: {
    siege_social: false,
    etablissement_siege_siret: "32922456200630",
    siret: "32922456200234",
    siren: "329224562",
    naf_code: "8559B",
    naf_libelle: "Autres enseignements",
    tranche_effectif_salarie: {
      de: 20,
      a: 49,
      code: "12",
      date_reference: "2018",
      intitule: "20 à 49 salariés",
    },
    date_creation: 851986800,
    date_mise_a_jour: 1598344422,
    diffusable_commercialement: true,
    enseigne: null,
    adresse: "LA COMPAGNIE DE FORMATION\r\n" + "1702 RUE SAINT PRIEST\r\n" + "34090 MONTPELLIER\r\n" + "FRANCE",
    numero_voie: "1702",
    type_voie: "RUE",
    nom_voie: "SAINT PRIEST",
    complement_adresse: null,
    code_postal: "34090",
    num_departement: "34",
    nom_departement: "Hérault",
    nom_academie: "Montpellier",
    num_academie: 11,
    localite: "MONTPELLIER",
    code_insee_localite: "34172",
    cedex: null,
    date_fermeture: "1970-01-01T00:00:00.000Z",
    ferme: false,
    region_implantation_code: "76",
    region_implantation_nom: "Occitanie",
    region: "Occitanie",
    num_region: "76",
    commune_implantation_code: "34172",
    commune_implantation_nom: "Montpellier",
    pays_implantation_code: "FR",
    pays_implantation_nom: "FRANCE",
    entreprise_siren: "329224562",
    entreprise_procedure_collective: false,
    entreprise_enseigne: null,
    entreprise_numero_tva_intracommunautaire: "FR07329224562",
    entreprise_code_effectif_entreprise: "32",
    entreprise_forme_juridique_code: "5710",
    entreprise_forme_juridique: "SAS, société par actions simplifiée",
    entreprise_raison_sociale: "LA COMPAGNIE DE FORMATION",
    entreprise_nom_commercial: "",
    entreprise_capital_social: 349298,
    entreprise_date_creation: 452988000,
    entreprise_date_radiation: null,
    entreprise_naf_code: "8559B",
    entreprise_naf_libelle: "Autres enseignements",
    entreprise_date_fermeture: null,
    entreprise_ferme: false,
    entreprise_siret_siege_social: "32922456200630",
    entreprise_nom: null,
    entreprise_prenom: null,
    entreprise_categorie: "ETI",
    entreprise_tranche_effectif_salarie: {
      de: 250,
      a: 499,
      code: "32",
      date_reference: "2018",
      intitule: "250 à 499 salariés",
    },
    computed_type: "OF",
    computed_conventionne: "NON",
    computed_declare_prefecture: "NON",
    catalogue_published: false,
    api_entreprise_reference: true,
    geo_coordonnees: "43.638208,3.83241",
    results_count: 1,
  },
  messages: { api_entreprise: "Ok", geo_coordonnees: "Ok" },
};

const rncpStubResult = {
  result: {
    cfds: ["40033006", "40033002"],
    code_rncp: "RNCP34605",
    intitule_diplome: "Animation - enfance et personnes âgées",
    date_fin_validite_enregistrement: "31/08/2025",
    active_inactive: "ACTIVE",
    etat_fiche_rncp: "Publiée",
    niveau_europe: "niveau4",
    code_type_certif: "BAC PRO",
    type_certif: "Baccalauréat professionnel",
    ancienne_fiche: ["RNCP4556"],
    nouvelle_fiche: null,
    demande: 0,
    certificateurs: [
      { certificateur: "Ministère de l'Education nationale et de la jeunesse", siret_certificateur: "11004301500012" },
    ],
    nsf_code: "330",
    nsf_libelle: "Spécialites plurivalentes des services aux personnes",
    romes: [
      { rome: "G1203", libelle: "Animation de loisirs auprès d'enfants ou d'adolescents" },
      { rome: "G1202", libelle: "Animation d'activités culturelles ou ludiques" },
    ],
    blocs_competences: [
      {
        numero_bloc: "RNCP34605BC10",
        intitule: "Histoire géographie et enseignement moral et civique",
        liste_competences:
          "<p>- Appréhender la diversité des sociétés et la richesse des cultures <br>- Comprendre les enjeux liés au développement durable <br>- Identifier les enjeux et contraintes de la mondialisation <br>- Identifier les droits et devoirs civils, politiques, économiques et sociaux  </p>",
        modalites_evaluation:
          "<p>  <strong>Candidats de la voie scolaire dans un établissement public ou privé sous contrat, CFA ou section d’apprentissage habilité, formation professionnelle continue dans un établissement public</strong> : ponctuel écrit   </p><p><br></p><p><strong>Candidats de la voie scolaire dans un établissement privé hors contrat, CFA ou section d’apprentissage non habilité, formation professionnelle continue dans un établissement privé, CNED, candidats justifiant de 3 années d’activité professionnelle</strong> : ponctuel écrit   </p><p><br></p><p><strong>Candidats de la formation professionnelle continue dans un établissement public habilité </strong>: contrôle en cours de formation (CCF) </p>",
      },
    ],
    voix_acces: null,
    partenaires: null,
    type_enregistrement: "Enregistrement de droit",
    si_jury_ca: "Oui",
    eligible_apprentissage: true,
    created_at: "2021-03-22T21:03:54.047Z",
    last_update_at: "2021-08-11T23:15:41.774Z",
    releated: [
      {
        cfd: {
          cfd: "40033006",
          cfd_outdated: false,
          date_fermeture: null,
          specialite: null,
          niveau: "4 (BAC...)",
          intitule_long: "ANIMATION - ENFANCE ET PERSONNES AGEES (BAC PRO)",
          intitule_court: "ANIMAT. ENFANCE& PERSONNES AGEES",
          diplome: "BAC PROFESSIONNEL",
          libelle_court: "BAC PRO",
          niveau_formation_diplome: "400",
        },
        mefs: {
          mefs10: [{ mef10: "2453300211", modalite: { duree: "1", annee: "1" } }],
          mefs8: ["24533002"],
          mefs_aproximation: [],
        },
      },
    ],
  },
  messages: {
    code_rncp: "Ok",
    releated: [
      {
        cfd: {
          cfd: "Trouvé dans la BCN",
          specialite: "Non fourni",
          niveau: "Ok",
          intitule_long: "Ok",
          intitule_court: "Ok",
          diplome: "Ok",
          libelle_court: "Ok",
          niveau_formation_diplome: "Ok",
        },
        mefs: { mefs10: "Ok", mefs8: "Ok", mefs_aproximation: "" },
      },
    ],
  },
};

const bcnStubResult = {
  formationsDiplomes: [
    {
      FORMATION_DIPLOME: "51025403",
      NIVEAU_FORMATION_DIPLOME: "510",
      GROUPE_SPECIALITE: "254",
      LETTRE_SPECIALITE: "S",
      ANCIEN_RECME: "510903",
      LIBELLE_COURT: "BEP",
      LIBELLE_STAT_33: "CARROSSERIE",
      LIBELLE_LONG_200: "CARROSSERIE (BEP)",
      DATE_OUVERTURE: "01/09/1994",
      DATE_FERMETURE: "31/08/2011",
      ANCIEN_DIPLOME_1: "51025402",
      ANCIEN_DIPLOME_2: "",
      ANCIEN_DIPLOME_3: "",
      ANCIEN_DIPLOME_4: "",
      ANCIEN_DIPLOME_5: "",
      ANCIEN_DIPLOME_6: "",
      ANCIEN_DIPLOME_7: "",
      NOUVEAU_DIPLOME_1: "",
      NOUVEAU_DIPLOME_2: "",
      NOUVEAU_DIPLOME_3: "",
      NOUVEAU_DIPLOME_4: "",
      NOUVEAU_DIPLOME_5: "",
      NOUVEAU_DIPLOME_6: "",
      NOUVEAU_DIPLOME_7: "",
      UNITE_CAPITALISABLE: "O",
      DATE_PREMIERE_SESSION: "1996",
      DATE_DERNIERE_SESSION: "2010",
      DATE_ARRETE_CREATION: "29/08/1994",
      DATE_ARRETE_ABROGATION: "28/07/2009",
      DATE_ARRETE_MODIFICATION_1: "04/02/2005",
      DATE_ARRETE_MODIFICATION_2: "20/10/2009",
      DATE_ARRETE_MODIFICATION_3: "",
      DATE_ARRETE_MODIFICATION_4: "",
      DATE_ARRETE_MODIFICATION_5: "",
      DATE_ARRETE_MODIFICATION_6: "",
      DATE_ARRETE_MODIFICATION_7: "",
      DATE_ARRETE_MODIFICATION_8: "",
      DATE_ARRETE_MODIFICATION_9: "",
      DATE_ARRETE_MODIFICATION_10: "",
      COMMENTAIRE: "A REMPLACE LE BEP DE MÊME INTITULE (51025402S). ABROGE SANS REMPLACEMENT.",
      NATURE_FORMATION_DIPLOME: "1",
      GESTIONNAIRE_FORMATION_DIPLOME: "DGESCO A2-3",
      DATE_INTERVENTION: "10/12/2020",
      NUMERO_COMPTE: "BCNVICTOR",
      GESTION_DIFFUSION: "02",
      NB_MEF_OUVERT: "0",
      NB_MEF_FERME: "3",
      ID_DOCUMENT: "",
      CITE_DOMAINE_FORMATION: "525",
      DATE_SESSION_RATTRAPAGE: "2011",
      OBSERVATION: "Grille horaire n°3 Production.",
      ID: "50",
      CREATED_AT: "",
      UPDATED_AT: "",
      N_COMMENTAIRE: "",
      CITE_DOMAINE_DETAILLE: "",
      created_at: "2021-03-22T17:25:09.866Z",
      last_update_at: "2021-08-11T23:02:17.827Z",
    },
  ],
  pagination: { page: 1, resultats_par_page: 10, nombre_de_page: 1, total: 1 },
};

const coordinatesStubResult = {
  result: { geo_coordonnees: "49.743252,4.730734", results_count: 1 },
  messages: { geo_coordonnees: "Ok" },
};

const addressStubResult = {
  result: {
    adresse: {
      numero_voie: "",
      type_voie: "",
      nom_voie: "Avenue Georges Brassens",
      code_postal: "31700",
      code_commune_insee: "31069",
      commune: "Blagnac",
      num_departement: "31",
      nom_departement: "Haute-Garonne",
      region: "Occitanie",
      num_region: "76",
      nom_academie: "Toulouse",
      num_academie: "16",
    },
    results_count: 1,
  },
  messages: { adresse: "Ok" },
};

const treeStubResult = {
  "3 (CAP...)": [
    "AUTRES DIPLOMES DE NIVEAU V",
    "BREVET D'ETUDES PROFESSIONNELLES",
    "BREVET D'ETUDES PROFESSIONNELLES AGRICOLES",
  ],
  "4 (BAC...)": ["BAC GENERAL", "BREVET DE TECHNICIEN AGRICOLE", "BREVET PROFESSIONNEL"],
  "5 (BTS, DEUST...)": [
    "CERTIFICAT DE SPECIALISATION AGRICOLE DE NIVEAU 3",
    "TH DE NIV 3 REMONTES DES CFA AGRICOLES",
    "TH DE NIV 3 SANTE SOCIAL",
  ],
  "6 (Licence, BUT...)": [
    "DIPLOME GRAND ETABLISSEMENT GRADE LICENCE",
    "LICENCE PROFESSIONNELLE",
    "TH DE NIV 2 REMONTES DES CFA AGRICOLES",
  ],
  "7 (Master, titre ingénieur...)": [
    "AUTRES DIPLOMES DE NIVEAU I",
    "TH DE NIV 1 MINISTERE INDUSTRIE",
    "TH DE NIV 1 NON PRECISE",
  ],
  "8 (Doctorat...)": [],
};

export const mock = {
  initTcoModel() {},
  getModels() {},
  rncpImporter() {},
  onisepImporter() {},
  bcnImporter() {},

  getCpInfo: () => cpStubResult,
  getRncpInfo: () => rncpStubResult,
  getCfdInfo: () => cfdStubResult,
  getMef10Info: () => mef10StubResult,
  getSiretInfo: () => siretStubResult,
  getBcnInfo: () => bcnStubResult,
  getCoordinatesFromAddressData: () => coordinatesStubResult,
  getAddressFromCoordinates: () => addressStubResult,
  getNiveauxDiplomesTree: () => treeStubResult,

  // don't mock this one, since it is just a computation
  async isValideUAI(uai: string) {
    return await isValideUAI(uai);
  },
};
