const { merge, mergeWith, isArray } = require("lodash");

const arrayMerger = (strategy) => (...args) =>
  mergeWith(...args, function (a, b) {
    if (isArray(a)) {
      switch (strategy) {
        case "merge":
          return merge(a, b);
        default:
          return b.concat(a);
      }
    }
  });

module.exports = {
  createApiGeoAddresseMock: (custom = {}) => {
    return {
      search() {
        return merge(
          {},
          {
            type: "FeatureCollection",
            version: "draft",
            features: [
              {
                type: "Feature",
                geometry: {
                  type: "Point",
                  coordinates: [2.396444, 48.879706],
                },
                properties: {
                  label: "31 Rue des Lilas 75019 Paris",
                  score: 0.7490827272727273,
                  housenumber: "31",
                  id: "75119_5683_00031",
                  name: "31 Rue des Lilas",
                  postcode: "75019",
                  citycode: "75119",
                  x: 655734.91,
                  y: 6864578.76,
                  city: "Paris",
                  district: "Paris 19e Arrondissement",
                  context: "75, Paris, Île-de-France",
                  type: "housenumber",
                  importance: 0.73991,
                  street: "Rue des Lilas",
                },
              },
            ],
            attribution: "BAN",
            licence: "ETALAB-2.0",
            query: '31 rue des lilas 75001 Paris"',
            limit: 5,
          },
          custom
        );
      },
    };
  },
  createApiEntrepriseMock: (custom = {}) => {
    return {
      getEtablissement() {
        return merge(
          {},
          {
            siege_social: true,
            siret: "11111111111111",
            naf: "6202A",
            libelle_naf: "Conseil en systèmes et logiciels informatiques",
            date_mise_a_jour: 1608114766,
            tranche_effectif_salarie_etablissement: {
              de: null,
              a: null,
              code: null,
              date_reference: null,
              intitule: null,
            },
            date_creation_etablissement: 1606431600,
            region_implantation: {
              code: "11",
              value: "Île-de-France",
            },
            commune_implantation: {
              code: "75000",
              value: "Paris",
            },
            pays_implantation: {
              code: "FR",
              value: "FRANCE",
            },
            diffusable_commercialement: true,
            enseigne: null,
            adresse: {
              l1: "NOMAYO",
              l2: null,
              l3: null,
              l4: "31 RUE DES LILAS",
              l5: null,
              l6: "75001 PARIS",
              l7: "FRANCE",
              numero_voie: "31",
              type_voie: "RUE",
              nom_voie: "DES LILAS",
              complement_adresse: null,
              code_postal: "75001",
              localite: "PARIS",
              code_insee_localite: "75000",
              cedex: null,
            },
            etat_administratif: {
              value: "A",
              date_fermeture: null,
            },
          },
          custom
        );
      },
    };
  },
  createApiEsSup: (custom = {}) => {
    return {
      async fetchInfoFromCodeCommune() {
        return merge(
          {},
          {
            nhits: 1,
            parameters: {
              dataset: "fr-esr-referentiel-geographique",
              refine: {
                com_code: "75001",
              },
              timezone: "UTC",
              rows: 1,
              start: 0,
              format: "json",
            },
            records: [
              {
                datasetid: "fr-esr-referentiel-geographique",
                recordid: "68784c1099e186e3aa8a3ed72d84d350e4d97bea",
                fields: {
                  com_code2: "75001",
                  reg_id_old: "R11",
                  com_code1: "75001",
                  au_code: "SO",
                  uucr_id: "SO",
                  aca_nom: "Paris",
                  com_nom_maj_court: "ALFORTVILLE",
                  uu_id_99: "SO",
                  regrgp_nom: "Île-de-France",
                  dep_code: "75",
                  au_id: "SO",
                  uu_id_10: "SO",
                  com_code: "75001",
                  aca_code: "01",
                  reg_code_old: "11",
                  dep_nom: "Paris",
                  aca_id: "A01",
                  com_nom_maj: "ALFORTVILLE",
                  com_nom: "Alfortville",
                  fr_id: "FR11",
                  reg_nom_old: "Île-de-France",
                  auc_nom: "SO",
                  com_id: "C75001",
                  fe_id: "FE1",
                  ze_id: "SO",
                  uucr_nom: "Alfortville",
                  fd_id: "FD111",
                  reg_code: "11",
                  dep_nom_num: "Paris (75)",
                  dep_num_nom: "75 - Paris",
                  reg_nom: "Île-de-France",
                  reg_id: "R11",
                  auc_id: "SO",
                  dep_id: "D075",
                  uu_id: "SO",
                },
                record_timestamp: "2020-11-23T13:58:15.677000+00:00",
              },
            ],
            facet_groups: [
              {
                facets: [
                  {
                    count: 1,
                    path: "75001",
                    state: "refined",
                    name: "75001",
                  },
                ],
                name: "com_code",
              },
            ],
          },
          custom
        );
      },
    };
  },
  createApiSireneMock: (custom = {}, options = {}) => {
    let mergeMockedData = options.array ? arrayMerger(options.array) : merge;
    return {
      getUniteLegale() {
        return mergeMockedData(
          {},
          {
            id: 129568762,
            siren: "111111111",
            statut_diffusion: "O",
            unite_purgee: null,
            date_creation: "2015-11-01",
            sigle: null,
            sexe: null,
            prenom_1: null,
            prenom_2: null,
            prenom_3: null,
            prenom_4: null,
            prenom_usuel: null,
            pseudonyme: null,
            identifiant_association: null,
            tranche_effectifs: "01",
            annee_effectifs: "2018",
            date_dernier_traitement: "2020-12-16T11:32:46",
            nombre_periodes: "3",
            categorie_entreprise: "PME",
            annee_categorie_entreprise: "2018",
            date_fin: null,
            date_debut: "2020-11-27",
            etat_administratif: "A",
            nom: null,
            nom_usage: null,
            denomination: "NOMAYO",
            denomination_usuelle_1: null,
            denomination_usuelle_2: null,
            denomination_usuelle_3: null,
            categorie_juridique: "5710",
            activite_principale: "62.02A",
            nomenclature_activite_principale: "NAFRev2",
            nic_siege: "11111",
            economie_sociale_solidaire: "N",
            caractere_employeur: "O",
            created_at: "2021-02-02T02:54:53.578+01:00",
            updated_at: "2021-02-02T02:54:53.578+01:00",
            etablissement_siege: {
              id: 276827433,
              siren: "111111111",
              nic: "11111",
              siret: "11111111111111",
              statut_diffusion: "O",
              date_creation: "2020-11-27",
              tranche_effectifs: null,
              annee_effectifs: null,
              activite_principale_registre_metiers: null,
              date_dernier_traitement: "2020-12-16T11:32:46",
              etablissement_siege: "true",
              nombre_periodes: "1",
              complement_adresse: null,
              numero_voie: "31",
              indice_repetition: "B",
              type_voie: "RUE",
              libelle_voie: "DES LILAS",
              code_postal: "75019",
              libelle_commune: "PARIS",
              libelle_commune_etranger: null,
              distribution_speciale: null,
              code_commune: "75000",
              code_cedex: null,
              libelle_cedex: null,
              code_pays_etranger: null,
              libelle_pays_etranger: null,
              complement_adresse_2: null,
              numero_voie_2: null,
              indice_repetition_2: null,
              type_voie_2: null,
              libelle_voie_2: null,
              code_postal_2: null,
              libelle_commune_2: null,
              libelle_commune_etranger_2: null,
              distribution_speciale_2: null,
              code_commune_2: null,
              code_cedex_2: null,
              libelle_cedex_2: null,
              code_pays_etranger_2: null,
              libelle_pays_etranger_2: null,
              date_debut: "2020-11-27",
              etat_administratif: "A",
              enseigne_1: null,
              enseigne_2: null,
              enseigne_3: null,
              denomination_usuelle: null,
              activite_principale: "62.02A",
              nomenclature_activite_principale: "NAFRev2",
              caractere_employeur: "O",
              longitude: "2.396147",
              latitude: "48.880391",
              geo_score: "0.88",
              geo_type: "housenumber",
              geo_adresse: "31 rue des lilas Paris 75019",
              geo_id: "75019_1475_00031_bis",
              geo_ligne: "G",
              geo_l4: "31 RUE DES LILAS",
              geo_l5: null,
              unite_legale_id: 129568762,
              created_at: "2021-02-02T17:46:40.046+01:00",
              updated_at: "2021-02-02T17:46:40.046+01:00",
            },
            numero_tva_intra: "FR74814562112",
            etablissements: [
              {
                id: 276827433,
                siren: "111111111",
                nic: "11111",
                siret: "11111111111111",
                statut_diffusion: "O",
                date_creation: "2020-11-27",
                tranche_effectifs: null,
                annee_effectifs: null,
                activite_principale_registre_metiers: null,
                date_dernier_traitement: "2020-12-16T11:32:46",
                etablissement_siege: "true",
                nombre_periodes: "1",
                complement_adresse: null,
                numero_voie: "31",
                indice_repetition: "B",
                type_voie: "RUE",
                libelle_voie: "DES LILAS",
                code_postal: "75001",
                libelle_commune: "PARIS",
                libelle_commune_etranger: null,
                distribution_speciale: null,
                code_commune: "75000",
                code_cedex: null,
                libelle_cedex: null,
                code_pays_etranger: null,
                libelle_pays_etranger: null,
                complement_adresse_2: null,
                numero_voie_2: null,
                indice_repetition_2: null,
                type_voie_2: null,
                libelle_voie_2: null,
                code_postal_2: null,
                libelle_commune_2: null,
                libelle_commune_etranger_2: null,
                distribution_speciale_2: null,
                code_commune_2: null,
                code_cedex_2: null,
                libelle_cedex_2: null,
                code_pays_etranger_2: null,
                libelle_pays_etranger_2: null,
                date_debut: "2020-11-27",
                etat_administratif: "A",
                enseigne_1: null,
                enseigne_2: null,
                enseigne_3: null,
                denomination_usuelle: null,
                activite_principale: "62.02A",
                nomenclature_activite_principale: "NAFRev2",
                caractere_employeur: "O",
                longitude: "2.396147",
                latitude: "48.880391",
                geo_score: "0.88",
                geo_type: "housenumber",
                geo_adresse: "31 rue des lilas Paris 75001",
                geo_id: "75001_1475_00031_bis",
                geo_ligne: "G",
                geo_l4: "31 RUE DES LILAS",
                geo_l5: null,
                unite_legale_id: 129568762,
                created_at: "2021-02-02T17:46:40.046+01:00",
                updated_at: "2021-02-02T17:46:40.046+01:00",
              },
            ],
          },
          custom
        );
      },
      getEtablissement() {
        return mergeMockedData(
          {},
          {
            id: 276827433,
            siren: "111111111",
            nic: "11111",
            siret: "11111111111111",
            statut_diffusion: "O",
            date_creation: "2020-11-27",
            tranche_effectifs: null,
            annee_effectifs: null,
            activite_principale_registre_metiers: null,
            date_dernier_traitement: "2020-12-16T11:32:46",
            etablissement_siege: "true",
            nombre_periodes: "1",
            complement_adresse: null,
            numero_voie: "31",
            indice_repetition: "B",
            type_voie: "RUE",
            libelle_voie: "DES LILAS",
            code_postal: "75019",
            libelle_commune: "PARIS",
            libelle_commune_etranger: null,
            distribution_speciale: null,
            code_commune: "75000",
            code_cedex: null,
            libelle_cedex: null,
            code_pays_etranger: null,
            libelle_pays_etranger: null,
            complement_adresse_2: null,
            numero_voie_2: null,
            indice_repetition_2: null,
            type_voie_2: null,
            libelle_voie_2: null,
            code_postal_2: null,
            libelle_commune_2: null,
            libelle_commune_etranger_2: null,
            distribution_speciale_2: null,
            code_commune_2: null,
            code_cedex_2: null,
            libelle_cedex_2: null,
            code_pays_etranger_2: null,
            libelle_pays_etranger_2: null,
            date_debut: "2020-11-27",
            etat_administratif: "A",
            enseigne_1: null,
            enseigne_2: null,
            enseigne_3: null,
            denomination_usuelle: null,
            activite_principale: "62.02A",
            nomenclature_activite_principale: "NAFRev2",
            caractere_employeur: "O",
            longitude: "2.396147",
            latitude: "48.880391",
            geo_score: "0.88",
            geo_type: "housenumber",
            geo_adresse: "31 rue des lilas Paris 75019",
            geo_id: "75019_1475_00031_bis",
            geo_ligne: "G",
            geo_l4: "31 RUE DES LILAS",
            geo_l5: null,
            unite_legale_id: 129568762,
            created_at: "2021-02-02T17:46:40.046+01:00",
            updated_at: "2021-02-02T17:46:40.046+01:00",
          },
          custom
        );
      },
    };
  },
};
