name: Deploy
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - shell: bash
        run: echo '::set-env name=TABLES_CORRESPONDANCES_HEAD_REF::${{ github.head_ref }}'
      
      - shell: bash
        run: echo '::set-env name=TABLES_CORRESPONDANCES_REF::${{ github.ref }}'

      - name: Check output
        run: echo ${TABLES_CORRESPONDANCES_REF:-${TABLES_CORRESPONDANCES_REF##*/}}

      - name: Request deployment
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mission-apprentissage/tables-correspondances-infra
          token: ${{ secrets.DEVOPS_ACCESS_TOKEN }}
          event-type: deploy
          client-payload: '{"envName": "recette", "branchName":"${{ github.head_ref }}"}'
        if: github.ref == 'ref/head/develop'
