# Worflow pour IC
name: Yarn CI Server

on: [push]

jobs:
  # Single job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository
      - uses: actions/checkout@v2


      - shell: bash
        run: echo '::set-env name=TABLES_CORRESPONDANCES_HEAD_REF::${{ github.head_ref }}'
      
      - shell: bash
        run: echo '::set-env name=TABLES_CORRESPONDANCES_REF::${{ github.ref }}'

      - name: Check output
        run: echo ${TABLES_CORRESPONDANCES_REF:-${TABLES_CORRESPONDANCES_REF##*/}}

      # Install dependencies
      - name: Run Yarn Install
        run: |
          cd server
          yarn install

      # Lint
      - name: Run Lint
        run: |
          cd server
          yarn lint

      # Start dockers containers
      - name: Start Docker
        run: |
          cd server
          yarn docker:start

      # Run mocha tests
      - name: Run Tests
        run: |
          cd server
          yarn test
